const express = require('express');
const authMiddleware = require('../middleware/auth');
const { getShareCardType } = require('../middleware/tierGating');
const { asyncHandler } = require('../middleware/errorHandler');
const { db } = require('../config/database');
const logger = require('../utils/logger');

const router = express.Router();

// POST /api/share-card/generate - Generate share card
router.post('/generate',
  authMiddleware,
  getShareCardType,
  asyncHandler(async (req, res) => {
    const { scanId } = req.body;
    const cardType = req.shareCardType; // 'free' or 'premium'

    if (!scanId) {
      return res.status(400).json({
        error: true,
        message: 'Scan ID is required',
      });
    }

    // Get scan data
    const scan = await db.getScanById(scanId);
    if (!scan || scan.user_id !== req.user.id) {
      return res.status(404).json({
        error: true,
        message: 'Scan not found',
      });
    }

    // Get user data
    const user = await db.getUserById(req.user.id);

    // Get leaderboard rank if premium
    let leaderboardRank = null;
    if (cardType === 'premium') {
      const { rows } = await db.query(
        'SELECT rank FROM leaderboard WHERE user_id = $1',
        [req.user.id]
      );
      leaderboardRank = rows[0]?.rank || null;
    }

    // Generate card data
    const cardData = {
      type: cardType,
      user: {
        name: user.name,
        profilePhoto: user.profile_photo_url || '/default-avatar.png',
      },
      scan: {
        glowScore: scan.glow_score,
        skinType: scan.skin_type,
        pimpleSeverity: scan.analysis?.issues?.acne?.severity || 'None',
        ageEstimation: scan.analysis?.age_estimation || null,
        timestamp: scan.created_at,
      },
    };

    // Add premium-only data
    if (cardType === 'premium') {
      cardData.premium = {
        streak: user.current_streak || 0,
        leaderboardRank: leaderboardRank,
        totalScans: user.total_scans || 0,
      };

      // Get before/after if available
      const { rows: previousScans } = await db.query(
        `SELECT glow_score, created_at 
         FROM scans 
         WHERE user_id = $1 AND id != $2 
         ORDER BY created_at ASC 
         LIMIT 1`,
        [req.user.id, scanId]
      );

      if (previousScans.length > 0) {
        cardData.premium.beforeAfter = {
          before: previousScans[0].glow_score,
          after: scan.glow_score,
          improvement: scan.glow_score - previousScans[0].glow_score,
        };
      }
    }

    // Save share card to database
    const { rows } = await db.query(
      `INSERT INTO share_cards (user_id, scan_id, card_type, card_url)
       VALUES ($1, $2, $3, $4)
       RETURNING id, card_url`,
      [req.user.id, scanId, cardType, null] // card_url will be generated by frontend
    );

    const shareCardId = rows[0].id;

    // Increment user's share count
    await db.query(
      'UPDATE users SET share_count = share_count + 1 WHERE id = $1',
      [req.user.id]
    );

    logger.info('Share card generated', {
      userId: req.user.id,
      scanId,
      cardType,
      shareCardId,
    });

    res.json({
      success: true,
      message: 'Share card generated successfully',
      data: {
        shareCardId,
        cardData,
        shareUrl: `${process.env.FRONTEND_URL}/share/${shareCardId}`,
      },
    });
  })
);

// GET /api/share-card/:id - Get share card data
router.get('/:id',
  asyncHandler(async (req, res) => {
    const { id } = req.params;

    const { rows } = await db.query(
      `SELECT 
        sc.*,
        u.name as user_name,
        u.profile_photo_url,
        s.glow_score,
        s.skin_type,
        s.analysis
      FROM share_cards sc
      JOIN users u ON sc.user_id = u.id
      JOIN scans s ON sc.scan_id = s.id
      WHERE sc.id = $1`,
      [id]
    );

    if (rows.length === 0) {
      return res.status(404).json({
        error: true,
        message: 'Share card not found',
      });
    }

    const card = rows[0];

    // Increment share count
    await db.query(
      'UPDATE share_cards SET share_count = share_count + 1 WHERE id = $1',
      [id]
    );

    res.json({
      success: true,
      data: {
        type: card.card_type,
        user: {
          name: card.user_name,
          profilePhoto: card.profile_photo_url || '/default-avatar.png',
        },
        scan: {
          glowScore: card.glow_score,
          skinType: card.skin_type,
          analysis: card.analysis,
        },
        createdAt: card.created_at,
      },
    });
  })
);

// POST /api/share-card/:id/track - Track share platform
router.post('/:id/track',
  authMiddleware,
  asyncHandler(async (req, res) => {
    const { id } = req.params;
    const { platform } = req.body; // 'instagram', 'snapchat', 'whatsapp', 'download'

    await db.query(
      'UPDATE share_cards SET platform = $1 WHERE id = $2',
      [platform, id]
    );

    logger.info('Share tracked', {
      shareCardId: id,
      platform,
      userId: req.user.id,
    });

    res.json({
      success: true,
      message: 'Share tracked successfully',
    });
  })
);

// GET /api/share-card/user/history - Get user's share history
router.get('/user/history',
  authMiddleware,
  asyncHandler(async (req, res) => {
    const { rows } = await db.query(
      `SELECT 
        sc.id,
        sc.card_type,
        sc.share_count,
        sc.platform,
        sc.created_at,
        s.glow_score
      FROM share_cards sc
      JOIN scans s ON sc.scan_id = s.id
      WHERE sc.user_id = $1
      ORDER BY sc.created_at DESC
      LIMIT 20`,
      [req.user.id]
    );

    res.json({
      success: true,
      data: {
        shares: rows,
        total: rows.length,
      },
    });
  })
);

module.exports = router;
